@WeatherApi_HostAddress = http://localhost:5087

GET {{WeatherApi_HostAddress}}/weather/current?city=Karachi
###

GET {{WeatherApi_HostAddress}}/weather/forecast?city=Karachi&days=3
###
GET {{WeatherApi_HostAddress}}/health